services:
  jenkins:
    image: woo204/jenkins-with-dood:latest
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "20004:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock